# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def mdi_init
  uri = URI.parse('https://materialdesignicons.com/api/init')
  request = Net::HTTP::Get.new uri
  req_options = {
      use_ssl: uri.scheme == "https",
      verify_mode: OpenSSL::SSL::VERIFY_NONE,
  }

  response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
    http.request(request)
  end

  JSON.parse(response.body)
end

def mdi_package(id)
  uri = URI.parse("https://materialdesignicons.com/api/package/#{id}")
  request = Net::HTTP::Get.new uri
  req_options = {
      use_ssl: uri.scheme == "https",
      verify_mode: OpenSSL::SSL::VERIFY_NONE,
  }

  response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
    http.request(request)
  end

  JSON.parse(response.body)
end

def download_asset(icon)
  name = icon["name"]
  folder = "../icons/#{name}/res/#{name}_24pt.xcassets/#{name}_24pt.imageset"
  FileUtils.mkdir_p folder

  open("https://materialdesignicons.com/api/download/icon/png/#{icon["id"]}/24/000000/1/FFFFFF/0/0/0/#{name}") do |image|
    File.open("#{folder}/#{name}_24pt_1x.png", "wb") do |file|
      file.write(image.read)
    end
  end
  open("https://materialdesignicons.com/api/download/icon/png/#{icon["id"]}/48/000000/1/FFFFFF/0/0/0/#{name}") do |image|
    File.open("#{folder}/#{name}_24pt_2x.png", "wb") do |file|
      file.write(image.read)
    end
  end
  open("https://materialdesignicons.com/api/download/icon/png/#{icon["id"]}/72/000000/1/FFFFFF/0/0/0/#{name}") do |image|
    File.open("#{folder}/#{name}_24pt_3x.png", "wb") do |file|
      file.write(image.read)
    end
  end
  File.open("#{folder}/Contents.json", "w") do |file|
    json = {
        "images": [
            {
                "filename": "#{name}_24pt_1x.png",
                "idiom": "universal",
                "scale": "1x"
            },
            {
                "filename": "#{name}_24pt_2x.png",
                "idiom": "universal",
                "scale": "2x"
            },
            {
                "filename": "#{name}_24pt_3x.png",
                "idiom": "universal",
                "scale": "3x"
            }
        ],
        "info": {
            "author": "xcode",
            "template-rendering-intent": "template",
            "version": 1
        }
    }
    file.write json.to_json
  end
end

platform :ios do
  desc "Download icons from materialdesignicons.com and update icons in current repository"
  lane :update_icons do
    require 'json'
    require 'net/http'
    require 'fileutils'
    require "open-uri"

    init = mdi_init
    package_id = init["packages"].first["id"]

    icons = mdi_package(package_id)["icons"]
    icons.each do |icon|
      name = icon["name"]
      UI.message "Downloading #{name} ..."

      download_asset(icon)

      FileUtils.mkdir_p "../icons/#{name}/src"
      sh("swiftgen run xcassets --output ../icons/#{name}/src/#{name}.swift --templateName swift5 --param publicAccess --param enumName MDIIcons --param imageType MDIIcon ../icons/#{name}/res/#{name}_24pt.xcassets")
    end
  end
  
  desc "Download icons metadata from materialdesignicons.com and update swift files in current repository"
  lane :update_swift do
    require 'json'
    require 'net/http'
    require 'fileutils'
    require "open-uri"
    require 'yaml'
    require 'active_support/core_ext/hash'

    swiftgen_xcassets = []

    init = mdi_init
    package_id = init["packages"].first["id"]

    icons = mdi_package(package_id)["icons"]
    icons.each do |icon|
      name = icon["name"]

      swiftgen_xcassets << {
          "inputs": "icons/#{name}/res/#{name}_24pt.xcassets",
          "outputs": [{
                          "templatePath": "templates/swift5-subspec.stencil",
                          "output": "icons/#{name}/src/#{name}.swift"
                      }]
      }
      FileUtils.mkdir_p "../icons/#{name}/src"
      #sh("swiftgen run xcassets --output ../icons/#{name}/src/#{name}.swift --templatePath ../templates/swift5-subspec.stencil ../icons/#{name}/res/#{name}_24pt.xcassets")
    end

    swiftgen_config = { "xcassets": swiftgen_xcassets }
    File.open("../swiftgen.yml", "w") { |file| file.puts swiftgen_config.deep_stringify_keys.to_yaml }
    Dir.chdir("..") do
      sh "swiftgen config run"
    end
  end

  desc "Download icons metadata from materialdesignicons.com and update swift files in current repository"
  lane :update_podspec do
    require 'json'
    require 'net/http'
    require 'fileutils'
    require "open-uri"

    podspec_path = "../MaterialDesignIcons.podspec.json"
    default_podspec = {
        "name": "MaterialDesignIcons",
        "version": "1.0.0",
        "summary": "View all the Material Design icons and more from the community.",
        "description": "Material Design Icons' growing icon collection allows designers and developers targeting various platforms to download icons in the format, color and size they need for any project.",
        "homepage": "https://materialdesignicons.com",
        "license": "Apache 2.0",
        "authors": { "Damien DANGLARD": "ddanglard@cegid.com" },
        "platforms": { "ios": "9.0" },
        "source": { "http": "https://github.com/friends-of-cocoa/material-design-icons/archive/1.0.0.zip", "type": "zip" },
        "swift_versions": "5.0",
        "osx": { "frameworks": "AppKit" },
        "ios": { "frameworks": "UIKit" },
        "watchos": { "frameworks": "UIKit" },
        "tvos": { "frameworks": "UIKit" }
    }
    podspec = File.exist?(podspec_path) ? JSON.parse(File.read(podspec_path)) : default_podspec
    podspec["subspecs"] = [{ "name": "core", "source_files": "icons/core/MDIIcon.swift" }]

    init = mdi_init
    package_id = init["packages"].first["id"]

    icons = mdi_package(package_id)["icons"]
    icons.each do |icon|
      name = icon["name"]

      swift_file = "icons/#{name}/src/#{name}.swift"
      xcassets_dir = "icons/#{name}/res/#{name}_24pt.xcassets"

      podspec["subspecs"] << {
          "name": name,
          "source_files": swift_file,
          "resource_bundles": { "#{name}": xcassets_dir },
          "dependencies": { "MaterialDesignIcons/core": [] }
      }
    end

    File.open("../MaterialDesignIcons.podspec.json", "w") { |file| file.puts JSON.pretty_generate(podspec) }
  end
end
